- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Install unzip
      ansible.builtin.apt:
        update_cache: yes
        name: unzip
  roles:
    - role: hth.deno
      vars:
        deno:
          primary: "2.8.2"
          versions:
            - version: "2.8.1"
              checksum: "sha256:2d7bb6195226ac832e0bf7109a115f0af65ee69ac797a4bbde5b27a06cc242d9"
            - version: "2.8.2"
              checksum: "sha256:184da7a5267ab649bc08821b3bc3ce6805d8e6985fb82707cb8d5e9fd6535362"
